#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

int main(){

    printf("Testing SIGSTOP\n");
    raise(SIGSTOP); //this signal can be generated by pressing ctr+z
    printf("We decided to continue\n\n");


    return 0;
}